CREATE TABLE [Provider].[Contractor] (
    [ID]                          UNIQUEIDENTIFIER NOT NULL,
    [ContractorName]              NVARCHAR (50)    NOT NULL,
    [DoingBusinessAs]             NVARCHAR (50)    NOT NULL,
    [ContractStartDate]           DATE             NOT NULL,
    [ContractEndDate]             DATE             NULL,
    [Status]                      NCHAR (2)        NOT NULL,
    [PhoneNumber]                 NVARCHAR (13)    NOT NULL,
    [AlternatePhoneNumber]        NVARCHAR (13)    NULL,
    [Type]                        NCHAR (2)        NOT NULL,
    [SuffixCode]                  NCHAR (2)        NULL,
    [Email]                       NVARCHAR (50)    NOT NULL,
    [ContactFirstName]            NVARCHAR (50)    NOT NULL,
    [ContactLastName]             NVARCHAR (50)    NOT NULL,
    [ContactPhoneNumber]          NVARCHAR (13)    NOT NULL,
    [ContactAlternatePhoneNumber] NVARCHAR (10)    NULL,
    [ContactEmail]                NVARCHAR (50)    NULL,
    [AddressLine1]                NVARCHAR (150)   NOT NULL,
    [AddressLine2]                NVARCHAR (150)   NULL,
    [City]                        NVARCHAR (50)    NOT NULL,
    [ZipCode]                     NCHAR (5)        NOT NULL,
    [ZipExntension]               NCHAR (4)        NULL,
    [StateCode]                   NCHAR (2)        NOT NULL,
    [FirstInsertedBy]             NVARCHAR (50)    NOT NULL,
    [FirstInsertedDateTime]       DATETIME         NOT NULL,
    [LastSavedBy]                 NVARCHAR (50)    NOT NULL,
    [LastSavedDateTime]           NCHAR (10)       NOT NULL,
    CONSTRAINT [PK_Provider]].[Contractor] PRIMARY KEY CLUSTERED ([ID] ASC)
);

